# Function to simulate a battle between two players
def battle(player1_health, player2_health):
    while player1_health > 0 and player2_health > 0:
        attack_player1 = random.randint(1, 20)
        attack_player2 = random.randint(1, 20)

        if attack_player1 > attack_player2:
            player2_health -= attack_player1 - attack_player2
        else:
            player1_health -= attack_player2 - attack_player1

    if player1_health > player2_health:
        return "Player 1 wins!"
    else:
        return "Player 2 wins!"

# Players' initial health
player1_health = 100
player2_health = 100

# Start the battle and print the result
result = battle(player1_health, player2_health)
print(result)
