# Define the Player class
class Player:
    def __init__(self, name, health):
        self.name = name
        self.health = health

    def attack(self, other):
        print(f"{self.name} attacks {other.name}!")
        damage = 10  # Define a static damage value for the sake of example
        other.health -= damage
        print(f"{other.name} loses {damage} health points.")

# Create two player instances
player1 = Player("Player 1", 100)
player2 = Player("Player 2", 100)

# Simulate a battle between the players
while player1.health > 0 and player2.health > 0:
    player1.attack(player2)
    player2.attack(player1)

# Determine the winner
if player1.health > player2.health:
    print(f"{player1.name} wins!")
else:
    print(f"{player2.name} wins!")
